---
- name: web-server confifuration
  hosts: web-servers
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx

- name: setup Mysql 
  become: yes
  hosts: Db-servers
  tasks:
    - name: Installing Mysql  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client 
       - python3-mysqldb
       - libmysqlclient-dev
      become: yes    

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes    

    - name: creating mysql user (medium_post)
      mysql_user:
        name: "MunaTeach"
        password: "Muna@11"
        priv: '*.*:ALL'
        host: '%'
        state: present   

    - name: creating agunigbo_db
      mysql_db:
        name: "MunaTeach"
        state: present    
        
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql  
         
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

- name: Install apache httpd
  hosts: Apache-Server
  become: true
  tasks:  
  - name: Install Apache Webserver
    apt: 
      name: apache2 
      update_cache: yes 
      state: latest
  - name: Enable Apache on system reboot
    service: 
      name: apache2
      enabled: yes
    notify: restart apache
  handlers:
  - name: restart apache
    service: 
      name: apache2 
      state: restarted


        
